name: Project Testing
run-name: ${{ github.actor }} is testing his project

on:
  push:
    branches:
    - main
    # paths:
    # - project/**

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # with:
        # path: main

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        # cache: 'pip'
    
    # test
    - name: Test
      run: |
        echo "ls"
        ls
        echo "ls home"
        ls ~
          
    # pip install
    - name: Install packages
      run: pip install -r project_requirements.txt

    # - name: Install packages
    #   shell: bash
    #   run: |
    #     pip install kaggle
    #     pip install pandas
    
    - name: Kaggle auth
      shell: bash
      run: |
        echo '{
          "username": "${{ secrets.KAGGLE_USERNAME }}",
          "key": "${{ secrets.KAGGLE_KEY }}"
        }' > kaggle.json
        mkdir -p ~/.kaggle
        mv kaggle.json ~/.kaggle/
        chmod 600 ~/.kaggle/kaggle.json
        echo "Kaggle login successful"

    # Run exercise feedback
    - name: Make test runnable
      run: chmod +x ./project/tests.sh
    - name: Project feedback
      run: |
        ./project/tests.sh