name: Project Testing
run-name: ${{ github.actor }} is testing his project

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        # cache: 'pip'
    
    # pip install
    - run: pip install -r project_requirements.txt

    # Run exercise feedback
    - name: Project feedback
      run: |
        ./project/tests.sh